const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Behaviors.bound,
		C3.Behaviors.Turret,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.LoadObjectTextures
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Player: 0},
	{Teclado: 0},
	{Mouse: 0},
	{MovimentoEmGrid: 0},
	{Fixar: 0},
	{jogador: 0},
	{Texto: 0},
	{Vida: 0},
	{portal: 0},
	{MoverPara: 0},
	{RestritoAoLayout: 0},
	{Canhão: 0},
	{inimigo2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{btnnão: 0},
	{btnsim: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{boss: 0},
	{Áudio: 0},
	{Sprite: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	jogador: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Vida: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	btnnão: class extends self.ISpriteInstance {},
	btnsim: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	boss: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {}
}